# SPDX-License-Identifier: GPL-3.0-only
#
# Copyright 2025-2026 Richard Thomson
#
name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # boost-parser build fails on macos-latest
        # os: [ ubuntu-latest, windows-latest, macos-latest ]
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683       # v4.2.2
      with:
        submodules: true

    - name: Setup vcpkg package cache
      id: vc
      uses: LegalizeAdulthood/vcpkg-github-cache@78a5438beedebc9fae6efb7bb8e3cc291d4d3f14
      with:
        token: ${{github.token}}
        bootstrap: "true"
        install-nuget: "true"
        debug: "false"
        trace: "false"

    - name: Install Prerequisites Linux
      if: ${{matrix.os == 'ubuntu-latest'}}
      shell: bash
      run: |
        echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
        sudo dpkg-reconfigure man-db
        sudo apt-get update
        sudo apt-get install -y \
          libxinerama-dev \
          libxcursor-dev \
          xorg-dev \
          libglu1-mesa-dev \
          pkg-config

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@802fa1a2c4e212495c05bf94dba2704a92a472be # v2.0.2
      with:
        cmake-version: '3.31'

    - name: Run Workflow
      shell: pwsh
      run: |
        cmake --version
        cmake --workflow --preset default 2>&1 |
          Tee-Object -FilePath build.log
        if ($LASTEXITCODE -ne 0) {
          exit $LASTEXITCODE
        }

    - name: Analyze vcpkg package cache
      if: always()
      uses: LegalizeAdulthood/vcpkg-github-cache/analyze@78a5438beedebc9fae6efb7bb8e3cc291d4d3f14
      with:
        token: ${{github.token}}
        build-log: build.log
        artifact-name: vcpkg-cache-diagnostics-${{github.job}}-${{matrix.os}}
        fail-on: "never"
        debug: "false"
        trace: "false"
